config/routes.rb
Rails.application.routes.draw do
  root "security#index"
  resources :genres
  resources :movies
  resources :personages
  get "security", to: "security#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: "log_in"
  delete "logout", to: "sessions#destroy"

  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  # makes Current.user accessible in view files.
  attribute :user
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_one_attached :photo
  has_many :movies, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :photo
  belongs_to :genre
  has_many :personages, dependent: :destroy

  def genres
    genres = Genre.all

    genres.map { |genre|
      genres = []
      genres << genre.name
      genres << genre.id
    }
  end

  def genre_name(id)
    genre = Genre.find(id)
    genre.name
  end
end

app/models/personage.rb
class Personage < ApplicationRecord
  has_one_attached :photo
  belongs_to :movie

  def movies
    movies = Movie.all

    movies.map { |movie|
      movies = []
      movies << movie.title
      movies << movie.id
    }
  end

  def movie_name(id)
    movies = Movie.find(id)
    movie.title
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Invalid email" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    # finds user with session data and stores it if present
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user_logged_in!
    # allows only logged in user
    redirect_to sign_in_path, alert: "You must be signed in" if Current.user.nil?
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_user_logged_in!

  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to @genre
    else
      render :new
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to @genre
    else
      render :edit
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to root_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_user_logged_in!

  def index
    pp params[:genre_id]
    @genres = Genre.all
    @movies = Movie.all

    if params[:genre_id]
      @movies = @movies.where(genre_id: params[:genre_id])
    end
    if params[:title]
      @movies = @movies.where(title: params[:title])
    end
    if params[:order] == "asc"
      @movies = Movie.order(creation_date: :asc)
    elsif params[:order] == "desc"
      @movies = Movie.order(creation_date: :desc)
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to root_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :creation_date, :score, :genre_id, :photo)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit; end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password Updated"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/personages_controller.rb
class PersonagesController < ApplicationController
  before_action :require_user_logged_in!

  def index
    pp params[:movie_id]
    @movies = Movie.all
    @personages = Personage.all
    if params[:movie_id]
      @personages = @personages.where(movie_id: params[:movie_id])
    end
    if params[:min_age].present?
      @personages = @personages.where("age >= ?", params[:min_age])
    end
    if params[:max_age].present?
      @personages = @personages.where("age <= ?", params[:max_age])
    end
    if params[:name]
      @personages = Personage.where(name: params[:name])
    end
  end

  def show
    @personage = Personage.find(params[:id])
  end

  def new
    @personage = Personage.new
  end

  def create
    @personage = Personage.new(personage_params)
    if @personage.save
      redirect_to @personage
    else
      render :new
    end
  end

  def edit
    @personage = Personage.find(params[:id])
  end

  def update
    @personage = Personage.find(params[:id])
    if @personage.update(personage_params)
      redirect_to @personage
    else
      render :edit
    end
  end

  private

  def personage_params
    params.require(:personage).permit(:name, :age, :weight, :history, :movie_id, :photo)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/security_controller.rb
class SecurityController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/genres/_form.html.erb
<%= form_with model: genre do |form| %>
    <%= form.text_field :name, placeholder: "name" %><br>
    <%= form.file_field :photo %><br>
    <%= form.submit "Submit", disable_with: "Submiting..." %>
<% end %>

app/views/genres/edit.html.erb
<h2>edit genre:</h2>
<%= render "form", genre: @genre %>

app/views/genres/index.html.erb
<h2>Genres:</h2>

<strong><%= link_to "Add new genre", new_genre_path %></strong> <br>

<% @genres.map { |genre| %>
    <%= link_to genre.name, genre %><br>
    <%= image_tag genre.photo if genre.photo.attached? %><br>

<% } %>
<br>

app/views/genres/new.html.erb
<h2>add new genre:</h2>
<%= render "form", genre: @genre %>

app/views/genres/show.html.erb
<p><%= @genre.name %> </p>
<%= image_tag @genre.photo if @genre.photo.attached? %>

<ul>
    <li>
        <%= link_to "edit", edit_genre_path(@genre) %>
    </li>

    <li>
        <%= link_to "destroy", genre_path(@genre), method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DisneyWorld</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
  <h1>THE WONDERFUL WORLD OF DISNEY</h1>
  <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with model: @movie do |form| %>
    <%= form.text_field :title, placeholder: "title" %><br>
    <%= form.date_field :creation_date, placeholder: "premiere" %><br>
    <%= form.label :score %>
    <%= form.select :score, [1, 2, 3, 4, 5] %><br>
    <%= form.select :genre_id, movie.genres %><br>
    <%= form.file_field :photo %><br>
    <%= form.submit "Submit", disable_with: "Submiting..." %>
<% end %>

app/views/movies/_genre.html.erb
<%= link_to movies_path(genre_id: genre.id) do %>
    <%= genre.name %><br>
<% end %>

app/views/movies/_movie.html.erb
<ul>
    <li>
        <%= link_to movie.title, movie %>
    </li>
    <li>
        <%= image_tag movie.photo if movie.photo.attached? %>
    </li>
    <li>
        <p><strong>creation date: </strong><%= movie.creation_date %></p>
    </li>
</ul>

app/views/movies/edit.html.erb
<h3>Edit movie</h3>
<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<h2>movies:</h2>

<%= link_to "Add new movie", new_movie_path %>

<h3>search movie for genre: </h3>
<%= link_to "All movies", movies_path %><br>
<%= render partial: "genre", collection: @genres %>

<h3>search movie for title: </h3>

<%= form_with url: movies_path, method: :get do |form| %>
    <%= form.text_field :title, placeholder: "title", value: params[:title] %>

    <%= form.submit "go", disable_with: "going..." %>
<% end %>

<h3>search movie for order: </h3>

<%= form_with url: movies_path, method: :get do |form| %>

    <%= form.select :order, [["ascending", "asc"], ["descending", "desc"]], value: params[:order] %>

    <%= form.submit "go", disable_with: "going..." %>
<% end %>

<%= render partial: "movie", collection: @movies %>

app/views/movies/new.html.erb
<h3>Add new movie</h3>
<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<h2><strong>"<%= @movie.title %>" the movie</strong></h2>
<%= image_tag @movie.photo if @movie.photo.attached? %>
<p><strong>creation date:</strong> <%= @movie.creation_date %></p>
<p><strong>genre:</strong> <%= @movie.genre_name(@movie.genre_id) %></p>

<h3>characters associated with this film:</h3>
<% @movie.personages.map { |personage| %>
    <p><%= personage.name %></p>
<% } %>

<ul>
    <li>
        <%= link_to "edit movie", edit_movie_path(@movie) %>
    </li>

    <li>
        <%= link_to "destroy movie", movie_path(@movie), method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
</ul>

app/views/personages/_form.html.erb
<%= form_with model: @personage do |form| %>

    <%= form.text_field :name, placeholder: "name" %><br>
    <%= form.text_field :age, placeholder: "age" %><br>
    <%= form.text_field :weight, placeholder: "weight" %><br>
    <%= form.text_field :history, placeholder: "history" %><br>
    <%= form.select :movie_id, personage.movies %><br>
    <%= form.file_field :photo %><br>
    <%= form.submit "Submit", disable_with: "Submiting..." %>
<% end %>

app/views/personages/_movie.html.erb
<%= link_to personages_path(movie_id: movie.id) do %>
    <%= movie.title %><br>
<% end %>

app/views/personages/_personage.html.erb
<ul>
    <li>
        <%= link_to personage.name, personage %>
    </li>

    <%= image_tag personage.photo if personage.photo.attached? %>
</ul>

app/views/personages/edit.html.erb
<h3>Edit personage</h3>

<%= render "form", personage: @personage %>

app/views/personages/index.html.erb
<h2>personages:</h2>

<p><strong><%= link_to "Add new personage", new_personage_path %></strong></p>


<h3>search personage for movie:</h3>
<%= link_to "All personages", personages_path %><br>
<%= render partial: "movie", collection: @movies %>

<h3>search personage for name: </h3>
<%= form_with url: personages_path, method: :get do |form| %>

    <%= form.text_field :name, placeholder: "name", value: params[:name] %>
    
    <%= form.submit "go", disable_with: "going..." %>

<% end %>

<h3>search personage for age:</h3>

<%= form_with url: personages_path, method: :get do |form| %>

    <%= form.number_field :min_age, placeholder: "min age", value: params[:min_age] %>
    <%= form.number_field :max_age, placeholder: "max age", value: params[:max_age] %>
    
    <%= form.submit "go", disable_with: "going..." %>

<% end %>

<%= render partial: "personage", collection: @personages %>  

app/views/personages/new.html.erb
<h3>Add new personage</h3>

<%= render "form", personage: @personage %>

app/views/personages/show.html.erb
<h3><strong><%= @personage.name %></strong></h3>
<%= image_tag @personage.photo if @personage.photo.attached? %>
<p><strong>age: </strong><%= @personage.age %> <br></p>
<p><strong>weight: </strong><%= @personage.weight %> <br></p>
<p><strong>history: </strong><%= @personage.history %> <br></p>
<p><strong>movie in which he appears: </strong> <%= @personage.movie_name(@personage.movie_id) %> <br></p>
<ul>
    <li>
        <%= link_to "edit", edit_personage_path(@personage) %>
    </li>

    <li>
        <%= link_to "destroy", personage_path(@personage), method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
</ul>

app/views/security/index.html.erb
<h2>Authentication</h2>

<% if Current.user %>
    Logged in as: <%= Current.user.email %><br>
    <%= link_to "Edit Password", edit_password_path %>
    <%= button_to "Logout", logout_path, method: :delete %>
    <% else %>
    <%= link_to "Sign Up", sign_up_path %>
    or
    <%= link_to "Login", sign_in_path %>
<% end %>
<br>
<br>
<br>
<br>

<%= link_to "touch me for dounload the orders", "/alkemy.pdf" %>

app/views/shared/_navbar.html.erb
<ul>
    <li>
        <%= link_to "account", root_path %>
    </li>
    <li>
        <%= link_to "genres", genres_path %>
    </li>
    <li>
        <%= link_to "movies", movies_path %>
    </li>
    <li>
        <%= link_to "personages", personages_path %>
    </li>
</ul>